### PR TITLE
Update appcompat 23.1.1

### PR DESCRIPTION
**Pull request by athospg**
buildToolsVersion 23.0.2;
Default FAM behavior for snackBar;
Replace ThemeUtils dependency with new class;

### CODE REVIEW

**Comment by taltstidl** [comment]
@athospg Awesome! Thanks. 
I'll test and merge this as soon as I can. Any specific reason why you removed the dependency on ThemeUtils?

**Comment by athospg** [comment]
@TR4Android Sorry, I forgot to say why I did that. They removed the ThemeUtils class from appcompat 23.1.1.

**Comment by athospg** [comment]
@TR4Android You should also remove the "Created by Athos on 01/12/2015.". It was automatic add by AndroidStudio and I forgot to remove.

**Comment by taltstidl** [comment]
@athospg That's what I thought. Thanks again for sending this pull request. Adding support for a default `Behaviour` has been on my personal list for a while now.

**Pull request merged**
